-- JKPSI 2017 Answer Key
-- Derived from question content — update answer_key and answer columns

UPDATE vaultcore.questions SET answer_key='D', answer='Microsoft Office' WHERE slug='jkpsi-2017-q1';
UPDATE vaultcore.questions SET answer_key='D', answer='(i), (ii) and (iii)' WHERE slug='jkpsi-2017-q2';
UPDATE vaultcore.questions SET answer_key='B', answer='5th June' WHERE slug='jkpsi-2017-q3';
UPDATE vaultcore.questions SET answer_key='C', answer='Keep the increase in global average temperature to well below 2°C above pre-industrial levels' WHERE slug='jkpsi-2017-q4';
UPDATE vaultcore.questions SET answer_key='D', answer='Kanishka' WHERE slug='jkpsi-2017-q5';
UPDATE vaultcore.questions SET answer_key='A', answer='Ministry of Home Affairs' WHERE slug='jkpsi-2017-q6';
UPDATE vaultcore.questions SET answer_key='D', answer='It was associated with Buddhism' WHERE slug='jkpsi-2017-q7';
UPDATE vaultcore.questions SET answer_key='B', answer='Wind energy' WHERE slug='jkpsi-2017-q8';
UPDATE vaultcore.questions SET answer_key='B', answer='Distance' WHERE slug='jkpsi-2017-q9';
UPDATE vaultcore.questions SET answer_key='D', answer='China' WHERE slug='jkpsi-2017-q10';
UPDATE vaultcore.questions SET answer_key='A', answer='Ireland' WHERE slug='jkpsi-2017-q11';
UPDATE vaultcore.questions SET answer_key='D', answer='(i) and (ii)' WHERE slug='jkpsi-2017-q12';
UPDATE vaultcore.questions SET answer_key='B', answer='Francois Bernier' WHERE slug='jkpsi-2017-q13';
UPDATE vaultcore.questions SET answer_key='D', answer='The Governor could be removed by a vote of no confidence to the Provincial legislature' WHERE slug='jkpsi-2017-q14';
UPDATE vaultcore.questions SET answer_key='C', answer='(i) and (iii) only' WHERE slug='jkpsi-2017-q15';
UPDATE vaultcore.questions SET answer_key='B', answer='Competition Commission of India' WHERE slug='jkpsi-2017-q16';
UPDATE vaultcore.questions SET answer_key='C', answer='Growth in food expenditure has been lower than growth in per capita income' WHERE slug='jkpsi-2017-q17';
UPDATE vaultcore.questions SET answer_key='C', answer='Rann of Kutch' WHERE slug='jkpsi-2017-q18';
UPDATE vaultcore.questions SET answer_key='B', answer='Providing LPG connections to all BPL households' WHERE slug='jkpsi-2017-q19';
UPDATE vaultcore.questions SET answer_key='C', answer='Odisha' WHERE slug='jkpsi-2017-q20';
UPDATE vaultcore.questions SET answer_key='B', answer='Chandragupta Maurya' WHERE slug='jkpsi-2017-q21';
UPDATE vaultcore.questions SET answer_key='C', answer='Hampi' WHERE slug='jkpsi-2017-q22';
UPDATE vaultcore.questions SET answer_key='B', answer='E.V.R. Naicker' WHERE slug='jkpsi-2017-q23';
UPDATE vaultcore.questions SET answer_key='C', answer='Non-Cooperation movement' WHERE slug='jkpsi-2017-q24';
UPDATE vaultcore.questions SET answer_key='D', answer='Kerala and Karnataka' WHERE slug='jkpsi-2017-q25';
UPDATE vaultcore.questions SET answer_key='B', answer='Kaveri' WHERE slug='jkpsi-2017-q26';
UPDATE vaultcore.questions SET answer_key='D', answer='It was formed due to tectonic activity' WHERE slug='jkpsi-2017-q27';
UPDATE vaultcore.questions SET answer_key='A', answer='Latitudinal extent' WHERE slug='jkpsi-2017-q28';
UPDATE vaultcore.questions SET answer_key='B', answer='Palk Strait and Gulf of Mannar' WHERE slug='jkpsi-2017-q29';
UPDATE vaultcore.questions SET answer_key='A', answer='The French Revolution' WHERE slug='jkpsi-2017-q30';
UPDATE vaultcore.questions SET answer_key='A', answer='Assam' WHERE slug='jkpsi-2017-q31';
UPDATE vaultcore.questions SET answer_key='C', answer='Initiating clotting of blood' WHERE slug='jkpsi-2017-q32';
UPDATE vaultcore.questions SET answer_key='A', answer='Amplitude' WHERE slug='jkpsi-2017-q33';
UPDATE vaultcore.questions SET answer_key='B', answer='Francois Bernier' WHERE slug='jkpsi-2017-q34';
UPDATE vaultcore.questions SET answer_key='D', answer='War, external aggression or armed rebellion' WHERE slug='jkpsi-2017-q35';
UPDATE vaultcore.questions SET answer_key='C', answer='Article 32' WHERE slug='jkpsi-2017-q36';
UPDATE vaultcore.questions SET answer_key='A', answer='Kathmandu' WHERE slug='jkpsi-2017-q37';
UPDATE vaultcore.questions SET answer_key='C', answer='Promoting financial inclusion in the country' WHERE slug='jkpsi-2017-q38';
UPDATE vaultcore.questions SET answer_key='D', answer='Arunachal Pradesh and Gujarat' WHERE slug='jkpsi-2017-q39';
UPDATE vaultcore.questions SET answer_key='D', answer='Neither (i) nor (ii)' WHERE slug='jkpsi-2017-q40';
UPDATE vaultcore.questions SET answer_key='B', answer='The jurisdictions of the Central and Provincial Governments' WHERE slug='jkpsi-2017-q41';
UPDATE vaultcore.questions SET answer_key='A', answer='Middle East' WHERE slug='jkpsi-2017-q42';
UPDATE vaultcore.questions SET answer_key='B', answer='Planning Commission' WHERE slug='jkpsi-2017-q43';
UPDATE vaultcore.questions SET answer_key='D', answer='Neither (i) nor (ii)' WHERE slug='jkpsi-2017-q44';
UPDATE vaultcore.questions SET answer_key='A', answer='Protect the interests of the Scheduled Tribes' WHERE slug='jkpsi-2017-q45';
UPDATE vaultcore.questions SET answer_key='C', answer='Directive Principles of State Policy' WHERE slug='jkpsi-2017-q46';
UPDATE vaultcore.questions SET answer_key='B', answer='Finland' WHERE slug='jkpsi-2017-q47';
UPDATE vaultcore.questions SET answer_key='A', answer='Nubra Valley Glacier — Arunachal Pradesh' WHERE slug='jkpsi-2017-q48';
UPDATE vaultcore.questions SET answer_key='B', answer='Shimla' WHERE slug='jkpsi-2017-q49';
UPDATE vaultcore.questions SET answer_key='B', answer='Oxygen' WHERE slug='jkpsi-2017-q50';
UPDATE vaultcore.questions SET answer_key='C', answer='(iii) and (iv) only' WHERE slug='jkpsi-2017-q51';
UPDATE vaultcore.questions SET answer_key='D', answer='hexagonal multilayer structure' WHERE slug='jkpsi-2017-q52';
UPDATE vaultcore.questions SET answer_key='B', answer='Nuclear Command Authority' WHERE slug='jkpsi-2017-q53';
UPDATE vaultcore.questions SET answer_key='A', answer='Article 14' WHERE slug='jkpsi-2017-q54';
UPDATE vaultcore.questions SET answer_key='C', answer='Vairengte' WHERE slug='jkpsi-2017-q55';
UPDATE vaultcore.questions SET answer_key='D', answer='Submarine' WHERE slug='jkpsi-2017-q56';
UPDATE vaultcore.questions SET answer_key='D', answer='Extend the territorial boundaries of the English East India Company' WHERE slug='jkpsi-2017-q57';
UPDATE vaultcore.questions SET answer_key='B', answer='The Zamindari system' WHERE slug='jkpsi-2017-q58';
UPDATE vaultcore.questions SET answer_key='C', answer='(i) only' WHERE slug='jkpsi-2017-q59';
UPDATE vaultcore.questions SET answer_key='B', answer='Anaemia' WHERE slug='jkpsi-2017-q60';
UPDATE vaultcore.questions SET answer_key='D', answer='Conservation of energy' WHERE slug='jkpsi-2017-q61';
UPDATE vaultcore.questions SET answer_key='C', answer='4' WHERE slug='jkpsi-2017-q62';
UPDATE vaultcore.questions SET answer_key='D', answer='Myanmar' WHERE slug='jkpsi-2017-q63';
UPDATE vaultcore.questions SET answer_key='C', answer='(iii) and (iv) only' WHERE slug='jkpsi-2017-q64';
UPDATE vaultcore.questions SET answer_key='B', answer='1 atmosphere' WHERE slug='jkpsi-2017-q65';
UPDATE vaultcore.questions SET answer_key='C', answer='Insulin' WHERE slug='jkpsi-2017-q66';
UPDATE vaultcore.questions SET answer_key='B', answer='Low partial pressure of oxygen' WHERE slug='jkpsi-2017-q67';
UPDATE vaultcore.questions SET answer_key='A', answer='A confession can never be used as evidence against the accused' WHERE slug='jkpsi-2017-q68';
UPDATE vaultcore.questions SET answer_key='C', answer='Bangkok' WHERE slug='jkpsi-2017-q69';
UPDATE vaultcore.questions SET answer_key='A', answer='Habeas Corpus' WHERE slug='jkpsi-2017-q70';
UPDATE vaultcore.questions SET answer_key='A', answer='An infantry regiment of the Indian Army' WHERE slug='jkpsi-2017-q71';
UPDATE vaultcore.questions SET answer_key='C', answer='Services' WHERE slug='jkpsi-2017-q72';
UPDATE vaultcore.questions SET answer_key='A', answer='It recommended the replacement of diarchy with responsible government in the provinces' WHERE slug='jkpsi-2017-q73';
UPDATE vaultcore.questions SET answer_key='A', answer='(i) and (ii) only' WHERE slug='jkpsi-2017-q74';
UPDATE vaultcore.questions SET answer_key='C', answer='Blood vessels, heart and blood' WHERE slug='jkpsi-2017-q75';
UPDATE vaultcore.questions SET answer_key='D', answer='Folding' WHERE slug='jkpsi-2017-q76';
UPDATE vaultcore.questions SET answer_key='B', answer='Stratosphere' WHERE slug='jkpsi-2017-q77';
UPDATE vaultcore.questions SET answer_key='C', answer='Slate' WHERE slug='jkpsi-2017-q78';
UPDATE vaultcore.questions SET answer_key='B', answer='Thermal power plants' WHERE slug='jkpsi-2017-q79';
UPDATE vaultcore.questions SET answer_key='D', answer='Chandrashekhar Azad' WHERE slug='jkpsi-2017-q80';
UPDATE vaultcore.questions SET answer_key='D', answer='Enamel of teeth' WHERE slug='jkpsi-2017-q81';
UPDATE vaultcore.questions SET answer_key='D', answer='Prairies' WHERE slug='jkpsi-2017-q82';
UPDATE vaultcore.questions SET answer_key='D', answer='Odisha' WHERE slug='jkpsi-2017-q83';
UPDATE vaultcore.questions SET answer_key='C', answer='Nitrogen' WHERE slug='jkpsi-2017-q84';
UPDATE vaultcore.questions SET answer_key='A', answer='(i) and (iii)' WHERE slug='jkpsi-2017-q85';
UPDATE vaultcore.questions SET answer_key='B', answer='Steel > Water > Wood' WHERE slug='jkpsi-2017-q86';
UPDATE vaultcore.questions SET answer_key='C', answer='More than 10 kgs' WHERE slug='jkpsi-2017-q87';
UPDATE vaultcore.questions SET answer_key='A', answer='India Gate' WHERE slug='jkpsi-2017-q88';
UPDATE vaultcore.questions SET answer_key='A', answer='(i) only' WHERE slug='jkpsi-2017-q89';
UPDATE vaultcore.questions SET answer_key='A', answer='Members of both the Houses of Parliament' WHERE slug='jkpsi-2017-q90';
UPDATE vaultcore.questions SET answer_key='D', answer='Parsis' WHERE slug='jkpsi-2017-q91';
UPDATE vaultcore.questions SET answer_key='B', answer='Champaran Satyagraha' WHERE slug='jkpsi-2017-q92';
UPDATE vaultcore.questions SET answer_key='A', answer='Union List' WHERE slug='jkpsi-2017-q93';
UPDATE vaultcore.questions SET answer_key='C', answer='13' WHERE slug='jkpsi-2017-q94';
UPDATE vaultcore.questions SET answer_key='A', answer='30' WHERE slug='jkpsi-2017-q95';
UPDATE vaultcore.questions SET answer_key='D', answer='20' WHERE slug='jkpsi-2017-q96';
UPDATE vaultcore.questions SET answer_key='D', answer='4 years' WHERE slug='jkpsi-2017-q97';
UPDATE vaultcore.questions SET answer_key='A', answer='C is the richest' WHERE slug='jkpsi-2017-q98';
UPDATE vaultcore.questions SET answer_key='D', answer='They never meet' WHERE slug='jkpsi-2017-q99';
UPDATE vaultcore.questions SET answer_key='D', answer='17 : 7' WHERE slug='jkpsi-2017-q100';
UPDATE vaultcore.questions SET answer_key='C', answer='88' WHERE slug='jkpsi-2017-q101';
UPDATE vaultcore.questions SET answer_key='B', answer='315 hectares' WHERE slug='jkpsi-2017-q102';
UPDATE vaultcore.questions SET answer_key='A', answer='10 a.m.' WHERE slug='jkpsi-2017-q103';
UPDATE vaultcore.questions SET answer_key='B', answer='Rs. 5.30' WHERE slug='jkpsi-2017-q104';
UPDATE vaultcore.questions SET answer_key='B', answer='700' WHERE slug='jkpsi-2017-q105';
UPDATE vaultcore.questions SET answer_key='C', answer='180°' WHERE slug='jkpsi-2017-q106';
UPDATE vaultcore.questions SET answer_key='D', answer='19' WHERE slug='jkpsi-2017-q107';
UPDATE vaultcore.questions SET answer_key='C', answer='4 m' WHERE slug='jkpsi-2017-q108';
UPDATE vaultcore.questions SET answer_key='A', answer='8/15' WHERE slug='jkpsi-2017-q109';
UPDATE vaultcore.questions SET answer_key='B', answer='20 years' WHERE slug='jkpsi-2017-q110';
UPDATE vaultcore.questions SET answer_key='B', answer='Tokyo' WHERE slug='jkpsi-2017-q111';
UPDATE vaultcore.questions SET answer_key='B', answer='Asia''s longest bi-directional tunnel' WHERE slug='jkpsi-2017-q112';
UPDATE vaultcore.questions SET answer_key='C', answer='Weight lifting' WHERE slug='jkpsi-2017-q113';
UPDATE vaultcore.questions SET answer_key='A', answer='Mithali Dorai Raj' WHERE slug='jkpsi-2017-q114';
UPDATE vaultcore.questions SET answer_key='D', answer='Child rights' WHERE slug='jkpsi-2017-q115';
UPDATE vaultcore.questions SET answer_key='B', answer='Provide a Rs. 5 lakh insurance cover to 10 crore economically vulnerable families' WHERE slug='jkpsi-2017-q116';
UPDATE vaultcore.questions SET answer_key='B', answer='Bengaluru' WHERE slug='jkpsi-2017-q117';
UPDATE vaultcore.questions SET answer_key='B', answer='The book was written in the 15th century' WHERE slug='jkpsi-2017-q118';
UPDATE vaultcore.questions SET answer_key='D', answer='(i), (ii) and (iii)' WHERE slug='jkpsi-2017-q119';
UPDATE vaultcore.questions SET answer_key='A', answer='Bud-shah' WHERE slug='jkpsi-2017-q120';
